# 로지스틱 회귀

<table align="left">
  <td>
    <a target="_blank" href="https://colab.research.google.com/github/rickiepark/hg-mldl/blob/master/4-1.ipynb"><img src="https://www.tensorflow.org/images/colab_logo_32px.png" />구글 코랩에서 실행하기</a>
  </td>
</table>

## 럭키백의 확률

### 데이터 준비하기

In [71]:
import pandas as pd

fish = pd.read_csv('https://bit.ly/fish_csv_data')
fish.head()

,Species,Weight,Length,Diagonal,Height,Width
0,Bream,242.0,25.4,30.0,11.5200,4.0200
1,Bream,290.0,26.3,31.2,12.4800,4.3056
2,Bream,340.0,26.5,31.1,12.3778,4.6961
3,Bream,363.0,29.0,33.5,12.7300,4.4555
4,Bream,430.0,29.0,34.0,12.4440,5.1340


In [72]:
print(pd.unique(fish['Species']))

['Bream' 'Roach' 'Whitefish' 'Parkki' 'Perch' 'Pike' 'Smelt']


In [73]:
fish_input = fish[['Weight','Length','Diagonal','Height','Width']].to_numpy()

In [74]:
print(fish_input[:5])

[[242.      25.4     30.      11.52     4.02  ]
 [290.      26.3     31.2     12.48     4.3056]
 [340.      26.5     31.1     12.3778   4.6961]
 [363.      29.      33.5     12.73     4.4555]
 [430.      29.      34.      12.444    5.134 ]]


In [75]:
fish_target = fish['Species'].to_numpy()

In [76]:
from sklearn.model_selection import train_test_split

train_input, test_input, train_target, test_target = train_test_split(
    fish_input, fish_target, random_state=42)

In [77]:
from sklearn.preprocessing import StandardScaler

ss = StandardScaler()
ss.fit(train_input)
train_scaled = ss.transform(train_input)
test_scaled = ss.transform(test_input)

### k-최근접 이웃 분류기의 확률 예측

In [78]:
from sklearn.neighbors import KNeighborsClassifier

kn = KNeighborsClassifier(n_neighbors=3)
kn.fit(train_scaled, train_target)

print(kn.score(train_scaled, train_target))
print(kn.score(test_scaled, test_target))

0.8907563025210085
0.85


In [79]:
print(kn.classes_)

['Bream' 'Parkki' 'Perch' 'Pike' 'Roach' 'Smelt' 'Whitefish']


In [80]:
print(kn.predict(test_scaled[:5]))

['Perch' 'Smelt' 'Pike' 'Perch' 'Perch']


In [81]:
import numpy as np

proba = kn.predict_proba(test_scaled[:5])
print(np.round(proba, decimals=4))

[[0.     0.     1.     0.     0.     0.     0.    ]
 [0.     0.     0.     0.     0.     1.     0.    ]
 [0.     0.     0.     1.     0.     0.     0.    ]
 [0.     0.     0.6667 0.     0.3333 0.     0.    ]
 [0.     0.     0.6667 0.     0.3333 0.     0.    ]]


In [82]:
distances, indexes = kn.kneighbors(test_scaled[3:4])
print(train_target[indexes])

[['Roach' 'Perch' 'Perch']]


In [84]:
import numpy as np

# 처음 5개 샘플에 대해 각각 최근접 이웃을 찾아 타깃 값과 확률을 함께 출력
distances, indexes = kn.kneighbors(test_scaled[:5])
proba = kn.predict_proba(test_scaled[:5])

for i, index in enumerate(indexes):
    prob_line = np.round(proba[i], decimals=4)
    # train_target[index] 배열을 str()로 감싸 문자열로 변환한 뒤 포맷팅을 적용합니다.
    print(f"샘플 {i}의 이웃 타깃: {str(train_target[index]):<25} | 확률: {prob_line}")

샘플 0의 이웃 타깃: ['Perch' 'Perch' 'Perch'] | 확률: [0. 0. 1. 0. 0. 0. 0.]
샘플 1의 이웃 타깃: ['Smelt' 'Smelt' 'Smelt'] | 확률: [0. 0. 0. 0. 0. 1. 0.]
샘플 2의 이웃 타깃: ['Pike' 'Pike' 'Pike']    | 확률: [0. 0. 0. 1. 0. 0. 0.]
샘플 3의 이웃 타깃: ['Roach' 'Perch' 'Perch'] | 확률: [0.     0.     0.6667 0.     0.3333 0.     0.    ]
샘플 4의 이웃 타깃: ['Perch' 'Perch' 'Roach'] | 확률: [0.     0.     0.6667 0.     0.3333 0.     0.    ]


## 로지스틱 회귀

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

z = np.arange(-5, 5, 0.1)
phi = 1 / (1 + np.exp(-z))

plt.plot(z, phi)
plt.xlabel('z')
plt.ylabel('phi')
plt.show()

### 로지스틱 회귀로 이진 분류 수행하기

In [ ]:
char_arr = np.array(['A', 'B', 'C', 'D', 'E'])
print(char_arr[[True, False, True, False, False]])

In [ ]:
bream_smelt_indexes = (train_target == 'Bream') | (train_target == 'Smelt')
train_bream_smelt = train_scaled[bream_smelt_indexes]
target_bream_smelt = train_target[bream_smelt_indexes]

In [ ]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()
lr.fit(train_bream_smelt, target_bream_smelt)

In [ ]:
print(lr.predict(train_bream_smelt[:5]))

In [ ]:
print(lr.predict_proba(train_bream_smelt[:5]))

In [ ]:
print(lr.classes_)

In [ ]:
print(lr.coef_, lr.intercept_)

In [ ]:
decisions = lr.decision_function(train_bream_smelt[:5])
print(decisions)

In [ ]:
from scipy.special import expit

print(expit(decisions))

### 로지스틱 회귀로 다중 분류 수행하기

In [ ]:
lr = LogisticRegression(C=20, max_iter=1000)
lr.fit(train_scaled, train_target)

print(lr.score(train_scaled, train_target))
print(lr.score(test_scaled, test_target))

In [ ]:
print(lr.predict(test_scaled[:5]))

In [ ]:
proba = lr.predict_proba(test_scaled[:5])
print(np.round(proba, decimals=3))

In [ ]:
print(lr.classes_)

In [ ]:
print(lr.coef_.shape, lr.intercept_.shape)

In [ ]:
decision = lr.decision_function(test_scaled[:5])
print(np.round(decision, decimals=2))

In [ ]:
from scipy.special import softmax

proba = softmax(decision, axis=1)
print(np.round(proba, decimals=3))